# AWESOME EDGE MACHINE LEARNING
---
title: Awesome Edge Machine Learning
description: A curated list of awesome edge machine learning resources, including research papers, inference engines, challenges, books, meetups and others.
url: https://github.com/bisonai/awesome-edge-machine-learning
filename: README.md
max_level: 2
badge:
  - "[![Awesome](https://awesome.re/badge-flat2.svg)](https://awesome.re)"
...
