# INFERENCE ENGINES
#
# [Template]
#
# description:
# sort_key:
# sort_reverse:
---
description: List of machine learning inference engines and APIs that are optimized for execution and/or training on edge devices.
sort_key: name
...
